### ISSUE TITLE
error in running track2p (non-square FOV)

### ISSUE THREAD

**Issue by rajatsaxena** [juremaj/track2p#2]
Thank you for providing this tool. I was testing this out on our CA1 2-photon imaging data analyzed using suite2p to track neurons across days and ran into the following problem. I've attached the programming error. Let me know if you need access to the raw data or I can dive more into the error. 

`
Directory already exists: C:/Users/Justin/Desktop/track2p-rajat/track2p/
Directory already exists: C:/Users/Justin/Desktop/track2p-rajat/track2p/fig/
Found 1 planes in C:\Users\Justin\Desktop\track2p-rajat\Data\10-25
Found 1 planes in C:\Users\Justin\Desktop\track2p-rajat\Data\10-30
Found 1 planes in C:\Users\Justin\Desktop\track2p-rajat\Data\11-1
Found 1 planes in C:\Users\Justin\Desktop\track2p-rajat\Data\11-3
Found 1 planes in all datasets
nchannels: 1 for plane 0 in dataset C:\Users\Justin\Desktop\track2p-rajat\Data\10-25
nchannels: 1 for plane 0 in dataset C:\Users\Justin\Desktop\track2p-rajat\Data\10-30
nchannels: 1 for plane 0 in dataset C:\Users\Justin\Desktop\track2p-rajat\Data\11-1
nchannels: 1 for plane 0 in dataset C:\Users\Justin\Desktop\track2p-rajat\Data\11-3
Found 1 channels in all datasets

Transforming ROIs for registration 0/3
Chose 443/444 ROIs, based on s2p iscell threshold 0.5 (see track_ops.iscell_thr)
Chose 422/423 ROIs, based on s2p iscell threshold 0.5 (see track_ops.iscell_thr)

IndexError                                Traceback (most recent call last)
Cell In[5], line 1
----> 1 run_t2p(track_ops)

File ~\Desktop\track2p-rajat\track2p\track2p\t2p.py:41, in run_t2p(track_ops)
     37 plot_reg_img_output(track_ops)
     40 # 5) apply computed transorm to all ROIs
---> 41 all_ds_all_roi_ref, all_ds_all_roi_mov, all_ds_all_roi_reg, all_ds_roi_counter = reg_all_ds_all_roi(all_ds_reg_params, track_ops)
     44 # 6) optional: generate 'yellow intersection' plot (this is only needed for plotting below)
     45 all_ds_ref_reg_inters = get_all_ref_nonref_inters(all_ds_all_roi_ref, all_ds_all_roi_reg, track_ops)

File ~\Desktop\track2p-rajat\track2p\track2p\register\loop.py:59, in reg_all_ds_all_roi(all_ds_reg_params, track_ops)
     56 stat_ref, roi_counter_ref = load_stat_ds_plane(ref_ds_path, track_ops, plane_idx=j) # loading rois for one dataset one plane
     57 stat_mov, roi_counter_mov = load_stat_ds_plane(reg_ds_path, track_ops, plane_idx=j) # loading rois for one dataset one plane
---> 59 all_roi_array_ref = get_all_roi_array_from_stat(stat_ref, track_ops) # for dataset i, plane j
     60 all_roi_array_mov = get_all_roi_array_from_stat(stat_mov, track_ops) # for dataset i, plane j
     62 # 3) Apply transformation

File ~\Desktop\track2p-rajat\track2p\track2p\io\loaders.py:39, in get_all_roi_array_from_stat(stat, track_ops)
     37     # Convert the ROI coordinates into a grid of values
     38     roi_grid = np.zeros((n_xpix, n_ypix), dtype=np.float32)
---> 39     roi_grid[np.array(roi_ypix), np.array(roi_xpix)] = 1
     41     all_roi_array[:,:,i] = roi_grid
     43 return all_roi_array

IndexError: index 506 is out of bounds for axis 1 with size 506
`

**Comment by juremaj** [comment]
Hi!
Thanks for bringing this up!

I think I know what might be causing this bug.
Are you using a non-square FOV in terms of pixels? I am assuming along either x or y it is 506 and the other is different, is that the case?

The thing is that we usually use a square FOV (512x512) so I didn't notice this error, but I found what in the code might be causing it.

Tell me if that's the case and I can push the appropriate changes.

Best,
Jure

**Comment by rajatsaxena** [comment]
Yes, I'm using a rectangular FOV with 506 x 480 pixels. Thank you!

**Comment by juremaj** [comment]
Hi!

Ok I've pushed the changes to Github, so you can try installing via Github instead of pip (instructions: https://track2p.github.io/install_via_github.html) and re-launching the algorithm to see if ti works now. 

There might be some other bugs related to this down the line, but you can check and let me know. If it keeps recurring I could also try debugging with your data in the worst case scenario.

-Jure

**Comment by rajatsaxena** [comment]
It works after commenting out this line in `loaders.py`:

`print(f'Loading ROIs for plane{plane_idx} in dataset {track_ops_path.split("/")[-2]}')`

I think it's because of window vs. linux file separator issue

**Comment by juremaj** [comment]
Perfect, thanks! I'll push the change and add both to the next pip version.
